"""Compute SHA-256 hashes of the frozen target_stats.json and norm_stats.json.

Emitted to preprocessed_data/stats_hashes.txt and checked into git. Every
RunPod pod verifies these hashes at startup (via scripts/sweep.py's
preflight) to detect stats-file drift between commits: the JSON artifacts
themselves live on the persistent volume / are regenerated by preprocessing,
so the git-tracked hash file is the record of which artifact contents the
committed code expects.

Run:    python -m Data.compute_stats_hashes            # write stats_hashes.txt
        python -m Data.compute_stats_hashes --verify   # exit 0 iff hashes match
        python -m Data.compute_stats_hashes --force    # overwrite on drift

This module itself depends only on hashlib/os/argparse (no torch, no numpy);
the path constants come from Data.config so they can never drift from what
training uses.
"""
import argparse
import os
import sys
from hashlib import sha256

from Data.config import NORM_STATS_PATH, TARGET_STATS_PATH

# Canonical order of the frozen artifacts; basename is the key in the file.
STATS_PATHS = (TARGET_STATS_PATH, NORM_STATS_PATH)
HASHES_PATH = os.path.join(os.path.dirname(TARGET_STATS_PATH),
                           'stats_hashes.txt')

DRIFT_MSG = (
    "Stats file drift detected. Either commit the updated stats_hashes.txt "
    "(if the JSONs changed intentionally, e.g. after preprocessing) or "
    "restore the JSONs (if they were accidentally modified)."
)


def _sha256_file(path):
    h = sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def compute_lines():
    """Current hashes as the exact lines stats_hashes.txt should contain."""
    return [f"{os.path.basename(p)}  {_sha256_file(p)}" for p in STATS_PATHS]


def read_lines(hashes_path=None):
    with open(hashes_path or HASHES_PATH) as f:
        return [line.rstrip('\n') for line in f if line.strip()]


def verify(hashes_path=None):
    """-> (ok, message). Recompute hashes and compare to stats_hashes.txt.

    Called in-process by scripts/sweep.py's preflight; the CLI --verify flag
    is a thin wrapper. Never raises on mismatch — missing files and drift
    both come back as (False, actionable message).
    """
    hashes_path = hashes_path or HASHES_PATH
    if not os.path.exists(hashes_path):
        return False, (f"{hashes_path} not found. Generate it with: "
                       f"python -m Data.compute_stats_hashes")
    for p in STATS_PATHS:
        if not os.path.exists(p):
            return False, (f"{p} not found. Run preprocessing and "
                           f"python -m Data.compute_target_stats first.")
    recorded, current = read_lines(hashes_path), compute_lines()
    if recorded == current:
        return True, f"stats hashes OK ({hashes_path})"
    diff = '\n'.join(
        f"  recorded: {r}\n  current:  {c}"
        for r, c in zip(recorded, current) if r != c
    ) or f"  recorded: {recorded}\n  current:  {current}"
    return False, f"{DRIFT_MSG}\nMismatch:\n{diff}"


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog='python -m Data.compute_stats_hashes',
        description='Freeze/verify SHA-256 hashes of the stats JSON artifacts.')
    parser.add_argument('--verify', action='store_true',
                        help='check stats_hashes.txt against the current JSONs '
                             'instead of writing; exit 1 on mismatch')
    parser.add_argument('--force', action='store_true',
                        help='overwrite an existing stats_hashes.txt whose '
                             'content would change')
    args = parser.parse_args(argv)

    if args.verify:
        ok, msg = verify()
        print(('[OK] ' if ok else '[ERROR] ') + msg)
        return 0 if ok else 1

    missing = [p for p in STATS_PATHS if not os.path.exists(p)]
    if missing:
        print(f"[ERROR] missing stats artifact(s): {missing}. Run "
              f"preprocessing / python -m Data.compute_target_stats first.")
        return 1

    lines = compute_lines()
    if os.path.exists(HASHES_PATH):
        if read_lines() == lines:
            print(f"[OK] {HASHES_PATH} already up to date.")
            return 0
        if not args.force:
            print(f"[ERROR] {HASHES_PATH} exists and content would change. "
                  f"{DRIFT_MSG}\nRe-run with --force to overwrite.")
            return 1

    with open(HASHES_PATH, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"[OK] wrote {HASHES_PATH}:")
    for line in lines:
        print(f"  {line}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
